### ISSUE TITLE
DatasetRecorder: Allow saveDataset to receive a dictionary of data sets instead of a list

### ISSUE THREAD

**Issue by clyde42069** [gone-still/ai#1]
The `saveDataset ` method should receive a `dict` containing a manual partition of datasets, just to avoid the automatic split if the used has already split their dataset.
Something like: `saveDataset(self, currentDataset: Union[list, dict], overwriteMode="Overwrite") -> dict`

**Comment by gone-still** [comment]
Added in aebab8476b0ad5779be86a3ec7d08c6d3ba1ce52

**Comment by gone-still** [comment]
Added in aebab8476b0ad5779be86a3ec7d08c6d3ba1ce52
